### PR TITLE
slyguy.paramount.plus: Implement playback sync and resume

### PR DESCRIPTION
**Pull request by StollD**
See also: https://github.com/matthuisman/slyguy.addons/issues/218#issuecomment-1678234450

This only implements syncing the current position to Paramount+ and resuming from it. The information for how to make a "Continue Watching" UI is also in the issue linked above, I will try to implement that later.

I have only tested this on the international / german Paramount+, but given how the rest of the API works, I imagine it will also work on the US version.

### CODE REVIEW

**Comment by matthuisman** [comment]
@StollD thanks for the amazing work!

Now merged in [v0.6.9](https://github.com/matthuisman/slyguy.addons/commit/07a78a06c1066221ff8edd3aea70b48155ddb288) with a few tweaks

**Comment by StollD** [comment]
I finally got around to testing this, but your changes unfortunately don't work for me.

The reason is that you are sending the wrong profile ID. It has to be the value of `referenceProfileId` in the structure from Paramount, but you are using `profile_id` from the userdata which is populated from `id`. I don't know if these two fields can be the same value, but for me they are different.

**Comment by matthuisman** [comment]
are you INT or US?
I was testing with US and pretty sure my referenceProfileId  was 0.
Maybe just need some if logic.
Ill try again tonight

**Comment by matthuisman** [comment]
so if you use referenceProfileId from above of 0 - the sync playback works ok?
I wonder how it knows what profile it is? Unless 0 means the "main profile" or something like that?

**Comment by matthuisman** [comment]
ok thanks :) just pushed 0.7.2 that will switch to using ref_id.
It may not work until your tokek is refreshed.
Re-selecting your profile should also do it

**Comment by StollD** [comment]
Can confirm that it works now. Thank you for fixing this so quickly!

**Pull request closed without merging**
