### PR TITLE
Patch to try and fix Hulu Live streaming

### PR DESCRIPTION
**Pull request by kcook98765**
Redid patch as the original addon updated which broke this drop in patch. Not tested, but should work.

### CODE REVIEW

**Comment by dapharsyde** [comment]
I gave this a try but ESPN stopped working after about 60 seconds.  I've attached a debug log in case it helps.  Let me know if there's anything else I can help provide, including loaning you my credentials.  Thanks for your efforts!
[kodi.proxy.test.log](https://github.com/matthuisman/slyguy.addons/files/14953695/kodi.proxy.test.log)

**Comment by kcook98765** [comment]
Logs show failure to parse the dash file by the original code (not the changes in the patch), so looks to be some other issue.

I had noticed a couple channels were not viewable when testing this in the past, but most others did work.

Are you able to watch other Live channel streams for more than a minute or 2?

**Comment by dapharsyde** [comment]
I tried some local channels, comedy central, FX, and food network and all
of them start stalling after receiving the no content manifest (response
204)

2024-04-12 13:10:44.347 T:9300    debug <general>: script.module.slyguy -
RESPONSE IN:
https://livem-ftc-na.media.hulustream.com/v1/live/dash/continue/594a157a-bf5b-4e74-a231-b8b6071d252b/manifest.mpd?cdns=af&cluster=blue&origin=us-west-2&duration=10800s&manifest_cdn=fa&repeat=true&patch=true&hpbsid_enabled=false&uas_enabled=false&segment_type_enabled=false&query_params_v2=false&unencrypted=false&cver=0&acquired_source_name=FOX_KTVU_SFO_MMA_LAS1-USW2&stream_filter=uhd_high_surround&prev_start=1712952627137&prev_boundary_start=1712952597107&prev_pts_values=AAC_1_CMAF_CENC_CTR%3D7649474560%7CEC3_1_CMAF_CENC_CTR%3D7649474653%7CH264_1_CMAF_CENC_CTR%3D9561842290&token=1712953240_841a5cdf3b571d1cd71438167eef8ef3915817ae2760f9bd1b50305b2003fea2
(204)
2024-04-12 13:10:44.348 T:9300    error <general>: script.module.slyguy -
Failed to parse dash:
2024-04-12 13:10:44.348 T:9300    error <general>: script.module.slyguy -
no element found: line 1, column 0

Let me know if there's anything else I can help provide in an effort to
troubleshoot this, thanks!

**Comment by kcook98765** [comment]
I might be able to look into this more next week when time permits, I think I have a local source to get Hulu login to test.

**Comment by dapharsyde** [comment]
hi @kcook98765 - just checking in to see if you've had a chance to look into this at all.  if needed, my offer of lending you my hulu credentials still stands.  thanks!

**Pull request closed without merging**
