### PR TITLE
feat(hbomax): pt-br translation

### PR DESCRIPTION
**Pull request by rokam**

### CODE REVIEW

**Comment by matthuisman** [comment]
Thank you very much.
A lot of the addons use common strings from my common module
https://github.com/matthuisman/slyguy.addons/tree/master/script.module.slyguy/resources/language

Maybe you would like to translate that too?

**Comment by rokam** [comment]
Sure, I'll do it.

**Comment by rokam** [comment]
Done #18

**Comment by matthuisman** [comment]
Awesome. Thank you very much

**Pull request closed without merging**
