### PR TITLE
Added Plex and Pluto

### PR DESCRIPTION
**Pull request by Asmodasis**
Fixed several bugs with pre-existing Plex and Pluto addon. Memory allocation caused crashing, stuttering, and desyncing issues on the stream. I believe the bugs are fixed by lowering the cache request.

### CODE REVIEW

**Comment by matthuisman** [comment]
hi @Asmodasis 
I cant spot your actual change to lower cache request?

It seems you have just PR'd the current version of the addons.
But I very well might be missing the actual change

Can you point to the line(s) you changed?

**Comment by Asmodasis** [comment]
Hello, I didn't change much. Line 53 in plugin.py (for both plex and
pluto) I changed  mem_cache.cached(60*15) to  mem_cache.cached(60*5), this
seemed to fix all the bugs I had, and the bugs I read about on the kodi
forums.

https://forum.kodi.tv/showthread.php?tid=357696&pid=3204389#pid3204389

I also updated the version number in both the xml files. (I noticed your
github had those removed so I added my versions that copied from
downloading your repo to Kodi.

I apologize if it wasn't clear, I'm still new to committing to open source.
I would be happy to keep helping out fixing bugs if I find any. I like
using your repo on Kodi.

  Thank you for your time.

**Comment by Asmodasis** [comment]
That's what I interpreted it as, which I thought would force the system to
redownload the file every 5 minutes. So, it should store less of the file.
It seemed like a weird fix, but at value 10 it has more bugs but less than
15. mem_cache seemed weird, so I wanted to look at it longer, but I have
this currently running on my TV (for my mom) and it's not
crashed,stuttered, or desynced once. (It used to do it every 10-20
minutes). If you feel it doesn't do anything, I'd be happy to continue
debugging, I figured I'd give something back to the code if I could.

   With regards,
     Shawn.

**Comment by Asmodasis** [comment]
Well, after about a week of testing it's doing it again, my apologies.
Please disregard the pull request and I'll get back to debugging.

    Thank you.

**Pull request closed without merging**
