### PR TITLE
script.module.slyguy: Allow to set a default resume mode

### PR DESCRIPTION
**Pull request by StollD**
My setup is ... a bit weird. A script on my NAS goes through a list of movies and tvshows and uses the API of the respective streaming service to download metadata. From this metadata, it generates nfo files and strm files pointing to the Kodi plugin for the service, which are then indexed by Jellyfin. The Jellyfin library is then synced into the Kodi library by the Jellyfin addon.

Essentially this means, that I am using these addons only for playback, I don't use the UI that they implement.

Now, the issue with this approach is that the current playback position is saved twice: Once in the Kodi/Jellyfin library, and once on the streaming service. I would like to use the resume logic of the Kodi library - e.g. with the time from Jellyfin, because I can edit that more easily than I could on a streaming service (mark as watched / unwatched).

However, this results in the popup that asks me from where to resume appearing twice, and ususally it completely breaks and resumes from wherever it wants.

I know that (at least for Disney+) I can disable the "Sync to Disney+" option, but I still would like my current playback position to by synced to Disney+ (so that the website at least somewhat represents what I watched, and so that my watches factor into their usage analysis).

Instead of just hacking together a bypass I decided to implement a proper option that allows the user to choose the resume behaviour, in case someone doesn't want to see the popup at all and prefers to always resume or always start from the beginning.

### CODE REVIEW

**Comment by matthuisman** [comment]
looks good. what does resume skip meant to do?

**Comment by StollD** [comment]
Yeah, I would use skip / bypass. I basically copied the naming for the quality selection, where its called SKIP in the code but bypass in the UI.

> The above code should stop kodi recording the position when sync is enabled.

I saw that but I didn't find any place where that option was actually used.

> How are you getting the position into Kodi?
> Your manually doing it?

Yes, as far as Kodi concerned its just a link to the plugins play method, and it is treated like any other (local) file.

**Comment by matthuisman** [comment]
i think ive got an easier fix for this.

I do like the thought of this - but i think the setting is a bit confusing as it doesnt automate kodis internal resume / from start

My thought is:

the addon when sync enabled generates play paths with .pvr so kodi ignores saving the playback data...
 
 So, if the play path doesnt get have this - then it should just bypass the resume as it cant be sure kodi wont show its own (as in your case)

**Comment by StollD** [comment]
So essentially the addon detects whether it is called from the "outside" and ignores the playback position? That would work too.

But wouldnt that require changes to every single addon? I really dont know much about the Kodi internals.

**Comment by matthuisman** [comment]
only need changes to my addons that have the "internal" resume from code (not many of them)

Please try latest Disney+ that just pushed (https://github.com/matthuisman/slyguy.addons/commit/7b13f85cd07ce1c14e312309661682ba7344ec4f)

**Comment by matthuisman** [comment]
have updated the other addons of mine with internal resume as well

**Pull request closed without merging**
