### PR TITLE
Update French translation of the Disney+ add-on

### PR DESCRIPTION
**Pull request by thombet**
* Create a file for French in France and update the file for French in Canada (both files are almost same but there seems to be no  way to use one file for both countries).
* Add a header to the English file so that `msgcmp` does not report any warning.
* Translate the summary of the add-on in addon.xml
* Translate to French the most used and basics strings in script.module.slyguy

### CODE REVIEW

**Comment by thombet** [comment]
@matthuisman  I didn't have the time (and the courage) to translate the whole language file for script.module.slyguy.

Some questions for you:

1. What does `Bypass` do regarding playback quality?
1. Same question for the setting `Video view for all content`
1. Same question for the setting `Folders for TV Show and Seasons`
1. Do you know if there is a way to have a single `strings.po`file for all the countries of the same language? I had to duplicate the files for `fr_fr`and `fr_ca` whereas it would be more effective to have a single file for both `fr_fr` and `fr_ca`...

**Comment by matthuisman** [comment]
awesome, thank you

1. bypass means that the proxy wont try to select the quality. itll just bypass the manifest "as is" to inputstream adaptive and let it choose what quality to play. Eventually when IA does adaptive switching, bypass would be renamed "Adaptive"
2. when this is enabled (default), the add-on will tell kodi that the list of content is all "videos". it won't set it to Movies for movies, tv shows for shows etc. This keeps the view consistent. However, some skins have better "eye candy" with this switched off.
3. Similar to above, with this enabled, the add-on wont tell kodi that a listing is a movie or show. That way, kodi will show the little folder icon for shows or movies which i believe makes telling what type of content it is easier. Either playable or browsable.
4. Thats a kodi language system thing. nothing the add-on can do about it unfortunately.

**Comment by thombet** [comment]
Thanks for the answers.

1. Oh ok I understand. Then what is the difference with `Disabled`?
1. I will have to modify the translation then.
1. I will also modify the translation.
1. I was just wondering if there is a way (at Kodi level) to achieve this because I am not an expert of Kodi add-on development. I tried naming the folder only `fr` (like in `addon.xml`) but it didn't work.

**Comment by thombet** [comment]
The PR is good to go now.
I just would like your answer to question 1 for my curiosity :)

By the way if you want to keep the translations up-to-date when you modify the English strings.po file you may tag me in an issue so that I update the French translation 😉

**Comment by matthuisman** [comment]
1) If you have it on disabled, you can choose "Play Quality" in the context menu on a video
  If you have bypass, you can manually still trigger the quality dialog via context.

One day I hope I can just spin up a weblate instance so that can keep the translations upto date

**Comment by matthuisman** [comment]
your changes are now in :)
thanks again

**Pull request closed without merging**
