### PR TITLE
Update api.py

### PR DESCRIPTION
**Pull request by JCalvi**
Randomize UDID for bot obfuscation

### CODE REVIEW

**Comment by JCalvi** [comment]
Part 1 of 2 of patches to work around akamai bot.

**Comment by camokarzi** [comment]
Confirmed this works  thanks mate you are a legend!

**Comment by JCalvi** [comment]
I don't have binge or foxtel so can't help with those.

**Comment by camokarzi** [comment]
I'd be happy to send you my login file so you could fix it.

**Comment by JCalvi** [comment]
Thanks for the offer, but will focus on Kayo for now. If I get spare time in future might look at the others.

**Comment by matthuisman** [comment]
thanks for the code. unfortunately this is not an approach i want to be taking.
Hopefully I can soon get back onto fixing these addons :)

**Pull request closed without merging**
