### PR TITLE
[ADD] disneyplus: support adding items to library

### PR DESCRIPTION
**Pull request by hbrunn**
adding to library works for series and movies, but you have to add $ADDON_PROFILE/{movies,series} manually to your library paths currently.

Missing features (not sure if they all need to be addressed in this PR):

1. add $ADDON_PROFILE/{movies,series} to library paths automatically on update/installation
2. have a background job that adds newly added episodes for added series
3. allow removing from library
4. give visual feedback when adding whole series to the library
5. ?write nfo files with metadata?

### CODE REVIEW

**Comment by matthuisman** [comment]
this looks pretty close for my plan for a generic add to library that i can do at the common layer.
My biggest issue I didnt want to sanitise the filenames from the content name.
I was hoping Kodi would allow me to just put the name in the nfo file.

then id name the strm as the content_id and have a nfo next to it with the title / year in it.
Then i wanted Kodi scrapers to pull the meta from the scrapers (fill in the missing info)

**Comment by hbrunn** [comment]
I've been dabbling with that this morning, but given

```shell
$ cat ~/.kodi/userdata/addon_data/slyguy.disney.plus/movies/141d2581-a35b-466c-b9c6-e660a1443876.nfo 
<?xml version='1.0' encoding='utf8'?>
<movie><title>The Creator</title><year>2023</year><premiered>2023-09-27</premiered></movie>

$ cat ~/.kodi/userdata/addon_data/slyguy.disney.plus/movies/141d2581-a35b-466c-b9c6-e660a1443876.strm 
plugin://slyguy.disney.plus/?_=play&content_id=141d2581-a35b-466c-b9c6-e660a1443876&profile_id=XXXX
```

I don't manage to have kodi's scrapers *amend* the info from the nfo file. I can only override all local data, but then it will search for the filename again. Am I missing something here?

For me this would mean back to the above, while possibly piping the name through https://pypi.org/project/pathvalidate and adding the year to the name?

**Comment by Kampfader** [comment]
@hbrunn 
Can you resolve this conflict? I would also be happy about this function in Disney plus.

**Comment by matthuisman** [comment]
@Kampfader ive just resolved the conflicts for you :)

**Comment by hbrunn** [comment]
@matthuisman what do you think about my [comment](https://github.com/matthuisman/slyguy.addons/pull/670#issuecomment-1913546214) above?

**Comment by matthuisman** [comment]
ive discussed that same thing on my ticket about adding add to library for all my addons
https://github.com/matthuisman/slyguy.addons/issues/14

I plan to do this in near future.
My plan is to use the content name (year).nfo as filename and keep the nfo empty due to exactly that nfo reason
Doesnt seem Kodi can grab partial nfo to help find the full info,

I thought Id commented about that issue somewhere but cant find it

**Pull request closed without merging**
